name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cmake-version: [3.20.0]
        build-type: [Release, Debug]

    steps:
    - uses: actions/checkout@v2
    - name: Set up CMake ${{ matrix.cmake-version }}
      uses: Kitware/setup-cmake@v1
      with:
        cmake-version: ${{ matrix.cmake-version }}
    - name: Build
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=${{ matrix.build-type }} && cmake --build build --config ${{ matrix.build-type }}
    - name: Test
      run: cd build && ctest --output-on-failure
